version: '3'
services:

  postgres:
    build:
        context: .
        dockerfile: Dockerfile
    image: my_postgres_116:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql.conf
    command: postgres -c config_file=/etc/postgresql.conf
    #when container_name is specified, as 
    #container name is always unique you cannot scale a service beyond 1 container
    container_name: postgresql_11_6
    restart: always    
    environment:
        #specify db name
        # POSTGRES_DB: postgres
        #default is postgres but custom it here for clarity
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres*116      
    ports:
      - "5116:5432"    
    #by defining the same "user defined network", all containers can talk to each other
    # networks:
    #   - appnet

#definition of all networks
# networks:
#   #with default settings (which is a load-balanced overlay network)
#   appnet:
      
#no need of volumes
# reference:
# http://aus800.com.au/building-a-postgresql-docker-container-with-debugger-pldebugger/